# Generated by Django 3.2.4 on 2021-06-14 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=250)),
                ('product_photo', models.FileField(upload_to='')),
                ('product_view_1', models.FileField(upload_to='')),
                ('product_view_2', models.FileField(upload_to='')),
                ('description', models.TextField(max_length=1000)),
                ('product_size', models.CharField(max_length=10)),
                ('product_price', models.DecimalField(decimal_places=0, max_digits=6)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.category')),
            ],
        ),
    ]
